name: Test setup-cvmfs action (with cvmfs_repositories)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@main
      with:
        cvmfs_repositories: 'grid.cern.ch'
    - name: Setup CernVM-FS
      run: cat /etc/cvmfs/default.local && ls /cvmfs/grid.cern.ch/ && cvmfs_config showconfig grid.cern.ch
