name: Test setup-cvmfs action (with cvmfs_repositories)
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
      with:
        cvmfs_repositories: 'eic.opensciencegrid.org'
    - name: Setup CernVM-FS
      run: cat /etc/cvmfs/default.local && ls /cvmfs/eic.opensciencegrid.org/
